repos:
  # General code quality and file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags in conda meta.yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Python linting and formatting with Ruff (replaces flake8, isort, black, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --line-length=120]
      # Run the formatter
      - id: ruff-format

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        files: \.py$
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-requests, types-PyYAML]


  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        files: Dockerfile.*

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: \.(sh|bash)$


  # YAML linting
#  - repo: https://github.com/adrienverge/yamllint
#    rev: v1.37.1
#    hooks:
#      - id: yamllint
#        files: \.(yaml|yml)$
#        args: [-d, relaxed]

#  # GitHub Actions workflow linting
#  - repo: https://github.com/rhysd/actionlint
#    rev: v1.7.7
#    hooks:
#      - id: actionlint

  # Rust code formatting and linting
#  - repo: https://github.com/doublify/pre-commit-rust
#    rev: v1.0
#    hooks:
#      - id: fmt
#        files: \.rs$
#      - id: clippy
#        files: \.rs$
#        args: [--all-targets, --all-features, ]

  # Check pyproject.toml files
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        files: pyproject\.toml$

  # Git hooks for better commit messages
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
