name: Build Rust Extension Wheels

# Builds wheels for Python packages with Rust extensions
# Uses cibuildwheel for cross-platform managers

on:
  push:
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        # setup uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: pypa/cibuildwheel@v3.0.0
        with:
          package-dir: packages/hello_rust

        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 pp* *musllinux*"  # we don't build for Windows 32-bit, PyPy or musllinux (fails)
          CIBW_BUILD_FRONTEND: "build[uv]"

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    if: false && startsWith(github.ref, 'refs/tags/') # HACK for tutorial purposes, remove in real use
    needs: build-wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1

#    upload_all:
#      needs: [ build_wheels, make_sdist ]
#      environment: pypi
#      permissions:
#        id-token: write
#        attestations: write
#        contents: read
#
#      runs-on: ubuntu-latest
#      if: github.event_name == 'release' && github.event.action == 'published'
#      steps:
#        - uses: actions/download-artifact@v4
#          with:
#            pattern: cibw-*
#            path: dist
#            merge-multiple: true
#
#        - name: Generate artifact attestations
#          uses: actions/attest-build-provenance@v2
#          with:
#            subject-path: "dist/*"
#
#        - uses: pypa/gh-action-pypi-publish@release/v1

